# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  infinispan.yaml: |
    infinispan:
      clusterName: infinispan-cluster
      zeroCapacityNode: false
      locks: {}
    jgroups:
      transport: tcp
      dnsPing:
        query: infinispan-ping.{{ .Release.Namespace }}.svc.cluster.local
      diagnostics: true
    xsite:
      address: ""
      name: ""
      port: 0
      backups: []
    endpoints:
      auth: true
      dedicatedAdmin: true
kind: ConfigMap
metadata:
  labels:
    app: infinispan-configmap-configuration
  name: infinispan-configuration