apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: infinispan-secret-admin-identities
  name: infinispan-generated-operator-secret
data: 
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IG9wZXJhdG9yCiAgcGFzc3dvcmQ6IDlrSVNVVmFvRmlqZm13OUIK
  # to decode  echo 'Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IG9wZXJhdG9yCiAgcGFzc3dvcmQ6IDlrSVNVVmFvRmlqZm13OUIK' | base64 --decode
  # identities.yaml:
  #   credentials:
  #     - username: operator
  #       password: 9kISUVaoFijfmw9B